#Trying a question based on strings understanding
print("Write a program that counts how many vowels are in a given string")
a= input("Enter a string: ").lower()
b = (a.count("a"))
print("number of 'a' in string is: ", b)
c =(a.count("e"))
print("number of 'e' in string is: ", c)
d = (a.count("i"))
print("number of 'i' in string is: ", d)
e=  (a.count("o"))
print("number of 'o' in string is: ")
print("number of 'u' in string is: ")
f= (a.count("u"))
print("Total vowels: ", b + c + d + e + f)